image: 
  name: kleinstein/immcantation:test

pipelines:
  default:
    - step:
        script:
          - sed -i '/test/ d' .Rbuildignore
          - Rscript tests/setup/install_dep.R
          - R CMD build .
          - R CMD check *.tar.gz --as-cran --run-donttest --timings
  lower-case:
    - step:
        script:
          - sed -i '/test/ d' .Rbuildignore
          - Rscript tests/setup/install_dep.R
          - Rscript -e "devtools::install_bitbucket('kleinstein/alakazam@IMM-29-lower-case-alakazam', upgrade = 'never')"
          - Rscript -e "devtools::install_bitbucket('kleinstein/shazam@lower-case', upgrade = 'never')"
          - R CMD build .
          - R CMD check *.tar.gz --as-cran --run-donttest --timings