site_name: tigger
site_favicon: img/immcantation.ico
theme: readthedocs
markdown_extensions:
  - def_list
  - sane_lists
  - smarty
  - toc:
      permalink: True
docs_dir: docs
pages:
  - 'About':
    - 'Introduction': index.md
    - 'Download & Installation': install.md
    - 'Package Overview': topics/tigger.md
    - 'Release Notes': news.md
    - 'Related Projects': projects.md
  - 'Vignettes':
    - 'Polymorphism detection and genotyping': vignettes/Tigger-Vignette.md
  - 'Help Topics':
    - 'Allele detection and genotyping':
      - topics/findNovelAlleles.md
      - topics/selectNovel.md
      - topics/inferGenotype.md
      - topics/inferGenotypeBayesian.md
      - topics/genotypeFasta.md
      - topics/reassignAlleles.md
      - topics/generateEvidence.md
      - topics/plotNovel.md
      - topics/plotGenotype.md
    - 'Mutation handling':
      - topics/getMutatedPositions.md
      - topics/getMutCount.md
      - topics/getPopularMutationCount.md
      - topics/findUnmutatedCalls.md
      - topics/insertPolymorphisms.md
    - 'File I/O and formatting':
      - topics/readIgFasta.md
      - topics/writeFasta.md
      - topics/cleanSeqs.md
      - topics/sortAlleles.md
      - topics/updateAlleleNames.md
    - 'Data':
      - topics/airrDb.md
      - topics/GermlineIGHV.md
      - topics/SampleDb.md
      - topics/SampleGenotype.md
      - topics/SampleNovel.md

