site_name: tigger
site_url: https://tigger.readthedocs.io
site_favicon: img/favicon.ico
repo_url: https://github.com/immcantation/tigger
edit_uri: src/master/docs/
theme:
  name: readthedocs
  navigation_depth: 2
  collapse_navigation: False
  sticky_navigation: False
  locale: en
  logo: null
  analytics:
    gtag: G-6HX7WPZEVH
markdown_extensions:
  - admonition
  - def_list
  - sane_lists
  - smarty
  - toc:
      permalink: True
      baselevel: 1
extra_javascript:
  - path: js/custom.js
    defer: true
docs_dir: docs
nav:
  - 'Immcantation Portal': https://immcantation.readthedocs.io/
  - 'About':
    - 'Introduction': index.md
    - 'Download & Installation': install.md
    - 'Contributing': contributing.md
    - 'Package Overview': topics/tigger.md
    - 'Release Notes': news.md
    - 'Related Projects': projects.md
  - 'Vignettes':
    - 'Polymorphism detection and genotyping': vignettes/Tigger-Vignette.md
  - 'Help Topics':
    - 'Allele detection and genotyping':
      - topics/findNovelAlleles.md
      - topics/selectNovel.md
      - topics/inferGenotype.md
      - topics/inferGenotypeBayesian.md
      - topics/genotypeFasta.md
      - topics/reassignAlleles.md
      - topics/generateEvidence.md
      - topics/plotNovel.md
      - topics/plotGenotype.md
    - 'Mutation handling':
      - topics/getMutatedPositions.md
      - topics/getMutCount.md
      - topics/getPopularMutationCount.md
      - topics/findUnmutatedCalls.md
      - topics/insertPolymorphisms.md
    - 'File I/O and formatting':
      - topics/readIgFasta.md
      - topics/writeFasta.md
      - topics/cleanSeqs.md
      - topics/sortAlleles.md
      - topics/subsampleDb.md
      - topics/updateAlleleNames.md
    - 'Data':
      - topics/AIRRDb.md
      - topics/GermlineIGHV.md
      - topics/SampleGermlineIGHV.md
      - topics/SampleDb.md
      - topics/SampleGenotype.md
      - topics/SampleNovel.md

